### ISSUE TITLE
Взрыв при открытии аудиозаписей

### ISSUE THREAD

**Issue by iGOR121** [openvk/mobile-android-legacy#166]
OpenVK Legacy 1.1.217 (3152dd8)
==============================================
DEVICE
Device: lge LM-G820N (codename: alphaplus)
Android: 10 (API 29)
==============================================
APP SETTINGS
Instance: openvk.su
HTTPS: Yes
Tablet UI?: No
==============================================
12-10 17:58:55.887 20100 20100 E AndroidRuntime: FATAL EXCEPTION: main
12-10 17:58:55.887 20100 20100 E AndroidRuntime: Process: uk.openvk.android.legacy, PID: 20100
12-10 17:58:55.887 20100 20100 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=uk.openvk.android.legacy.AP_UPDATE_CURRENT_TRACKPOS flg=0x10 (has extras) } in uk.openvk.android.legacy.receivers.AudioPlayerReceiver@b401ed9
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1561)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7557)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at uk.openvk.android.legacy.ui.list.adapters.AudiosListAdapter.setTrackState(AudiosListAdapter.java:93)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at uk.openvk.android.legacy.core.fragments.AudiosFragment.updateCurrentTrackPosition(AudiosFragment.java:256)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at uk.openvk.android.legacy.receivers.AudioPlayerReceiver.onReceive(AudioPlayerReceiver.java:45)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1551)
12-10 17:58:55.887 20100 20100 E AndroidRuntime: 	... 8 more
12-10 17:58:55.888 20100 20100 E ACRA    : ACRA caught a RuntimeException for uk.openvk.android.legacy
12-10 17:58:55.888 20100 20100 E ACRA    : java.lang.RuntimeException: Error receiving broadcast Intent { act=uk.openvk.android.legacy.AP_UPDATE_CURRENT_TRACKPOS flg=0x10 (has extras) } in uk.openvk.android.legacy.receivers.AudioPlayerReceiver@b401ed9
12-10 17:58:55.888 20100 20100 E ACRA    : 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1561)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:883)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at android.os.Looper.loop(Looper.java:214)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7557)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
12-10 17:58:55.888 20100 20100 E ACRA    : Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12-10 17:58:55.888 20100 20100 E ACRA    : 	at java.util.ArrayList.get(ArrayList.java:437)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at uk.openvk.android.legacy.ui.list.adapters.AudiosListAdapter.setTrackState(AudiosListAdapter.java:93)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at uk.openvk.android.legacy.core.fragments.AudiosFragment.updateCurrentTrackPosition(AudiosFragment.java:256)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at uk.openvk.android.legacy.receivers.AudioPlayerReceiver.onReceive(AudioPlayerReceiver.java:45)
12-10 17:58:55.888 20100 20100 E ACRA    : 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1551)
12-10 17:58:55.888 20100 20100 E ACRA    : 	... 8 more
12-10 17:58:56.077 20100 22960 E ACRA    : uk.openvk.android.legacy fatal error : Error receiving broadcast Intent { act=uk.openvk.android.legacy.AP_UPDATE_CURRENT_TRACKPOS flg=0x10 (has extras) } in uk.openvk.android.legacy.receivers.AudioPlayerReceiver@b401ed9
12-10 17:58:56.077 20100 22960 E ACRA    : java.lang.RuntimeException: Error receiving broadcast Intent { act=uk.openvk.android.legacy.AP_UPDATE_CURRENT_TRACKPOS flg=0x10 (has extras) } in uk.openvk.android.legacy.receivers.AudioPlayerReceiver@b401ed9
12-10 17:58:56.077 20100 22960 E ACRA    : 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1561)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:883)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at android.os.Looper.loop(Looper.java:214)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7557)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
12-10 17:58:56.077 20100 22960 E ACRA    : Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12-10 17:58:56.077 20100 22960 E ACRA    : 	at java.util.ArrayList.get(ArrayList.java:437)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at uk.openvk.android.legacy.ui.list.adapters.AudiosListAdapter.setTrackState(AudiosListAdapter.java:93)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at uk.openvk.android.legacy.core.fragments.AudiosFragment.updateCurrentTrackPosition(AudiosFragment.java:256)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at uk.openvk.android.legacy.receivers.AudioPlayerReceiver.onReceive(AudioPlayerReceiver.java:45)
12-10 17:58:56.077 20100 22960 E ACRA    : 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1551)
12-10 17:58:56.077 20100 22960 E ACRA    : 	... 8 more

**Comment by iGOR121** [comment]
по-моему уже unrelated, в 218 пофиксили
